<?php

/**
 * BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $news_id
 * @property integer $lang_id
 * @property varchar $newstitle
 * @property text $newsanons
 * @property text $newstext
 * @property NewsList $NewsList
 * 
 * @method integer  getId()        Returns the current record's "id" value
 * @method integer  getNewsId()    Returns the current record's "news_id" value
 * @method integer  getLangId()    Returns the current record's "lang_id" value
 * @method varchar  getNewstitle() Returns the current record's "newstitle" value
 * @method text     getNewsanons() Returns the current record's "newsanons" value
 * @method text     getNewstext()  Returns the current record's "newstext" value
 * @method NewsList getNewsList()  Returns the current record's "NewsList" value
 * @method News     setId()        Sets the current record's "id" value
 * @method News     setNewsId()    Sets the current record's "news_id" value
 * @method News     setLangId()    Sets the current record's "lang_id" value
 * @method News     setNewstitle() Sets the current record's "newstitle" value
 * @method News     setNewsanons() Sets the current record's "newsanons" value
 * @method News     setNewstext()  Sets the current record's "newstext" value
 * @method News     setNewsList()  Sets the current record's "NewsList" value
 * 
 * @package    newslist
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('news_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('lang_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('newstitle', 'varchar', null, array(
             'type' => 'varchar',
             ));
        $this->hasColumn('newsanons', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('newstext', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NewsList', array(
             'local' => 'lang_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}