<?php

/**
 * BaseLang
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property char $shortname
 * @property varchar $fullname
 * @property boolean $def
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method char    getShortname() Returns the current record's "shortname" value
 * @method varchar getFullname()  Returns the current record's "fullname" value
 * @method boolean getDef()       Returns the current record's "def" value
 * @method Lang    setId()        Sets the current record's "id" value
 * @method Lang    setShortname() Sets the current record's "shortname" value
 * @method Lang    setFullname()  Sets the current record's "fullname" value
 * @method Lang    setDef()       Sets the current record's "def" value
 * 
 * @package    newslist
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLang extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lang');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('shortname', 'char', 3, array(
             'type' => 'char',
             'length' => 3,
             ));
        $this->hasColumn('fullname', 'varchar', null, array(
             'type' => 'varchar',
             ));
        $this->hasColumn('def', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}