<?php

/**
 * BaseNewsList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $newsdate
 * @property varchar $newspicture
 * @property Doctrine_Collection $News
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method timestamp           getNewsdate()    Returns the current record's "newsdate" value
 * @method varchar             getNewspicture() Returns the current record's "newspicture" value
 * @method Doctrine_Collection getNews()        Returns the current record's "News" collection
 * @method NewsList            setId()          Sets the current record's "id" value
 * @method NewsList            setNewsdate()    Sets the current record's "newsdate" value
 * @method NewsList            setNewspicture() Sets the current record's "newspicture" value
 * @method NewsList            setNews()        Sets the current record's "News" collection
 * 
 * @package    newslist
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewsList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news_list');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'unique' => true,
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('newsdate', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('newspicture', 'varchar', null, array(
             'type' => 'varchar',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('News', array(
             'local' => 'id',
             'foreign' => 'lang_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}