<?php

/**
 * NewsListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsListTable
     */
    public function getNewsList()
    {
      $q = $this->createQuery('n')
        ->orderby('n.newsdate DESC LIMIT 5');
      return $q->execute();
    }


    public static function getInstance()
    {
        return Doctrine_Core::getTable('NewsList');
    }
}