<?php

/**
 * NewsList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    newslist
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NewsList extends BaseNewsList
{
   public function getNews($sla=1)
    {
        $q = Doctrine_Query::create()
        ->from('news n');
        $new=Doctrine_Core::getTable('news')->getNew($this->getId(),$sla,$q);
        return $new[0];
    }

}