<?php

/**
 * NewsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewsTable
     */
    public function getNew($id, $sla=1, Doctrine_Query $q = null)
    {
        if (is_null($q))
          {
            $q = Doctrine_Query::create()
            ->from('news n');
           }
        $q->andWhere('n.news_id = ?', $id)
        ->andWhere('n.lang_id = ?',$sla);
        return $q->execute();
    }


    public static function getInstance()
    {
        return Doctrine_Core::getTable('News');
    }
}